on:
  workflow_dispatch: 
  push:
    branches:
      - main
    tags:
      - "v*"  
jobs:
  dist:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Intall dependencies
        run: poetry install
  
      - name: Running tests
        run: poetry run test
          
      - name: Building dist
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    name: Publish to PyPI
    needs: dist
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          packages-dir: .

